CREATE TABLE IF NOT EXISTS todos (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    todo TEXT NOT NULL,
    complete tinyint(1),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

